### ISSUE TITLE
Run tests on Windows using Github actions?

### ISSUE THREAD

**Issue by jensens** [zopefoundation/zope.sendmail#32]
Since we have some windows specific parts in zope.sendmail: With Github actions it is relative easy to run tests on windows. Would it be an idea to add one (I can create this)? see also #30

**Comment by icemac** [comment]
I think you should be able to create a PR to try testing on Windows using GH Actions. However  there is no blueprint for this in the zopefoundation repositories.

**Comment by mgedmin** [comment]
We've successfully used Appveyor in the past.  I have zero experience with GH actions; a PR would be welcome, but if the important thing is to test on Windows, I could whip up a quick `appveyor.yml`.

**Comment by mgedmin** [comment]
Good thing I did: the error handling code is broken on Python 3 on Windows (exceptions are not subscriptable).  Fix in #33, along with an appveyor.yml.

**Comment by jensens** [comment]
Thanks @mgedmin 
I have no experience with nor an account at Appveyor. From our (Plone) experience it tends to be fragile, but I was not involved here, so it is what other told me. Anyway, I am w/o any emotions here as long as it tests the code.

If you're interested in an example how testing may look on Linux and Windows in one file with Github actions have a look at: https://github.com/plone/plone.recipe.zope2instance/blob/master/.github/workflows/testing.yml

One big advantage is, its all on one platform, Github. One  bigdisadvantage is, its all on one platform, Github. ;-)

**Comment by icemac** [comment]
The package is now CI tested on windows so I am going to close this issue.
