### ISSUE TITLE
Documentation at RTD outdated 

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.sendmail#40]
According to https://readthedocs.org/projects/zopesendmail/builds/ it was build 3 years ago the last time.

It seems we are missing a Webhooks as described in: https://docs.readthedocs.io/en/stable/webhooks.html

@jamadden is the only admin for this project at RTD – could you please fix this or add me (`icemac`) at RTD?

**Comment by jamadden** [comment]
@icemac Thanks for the heads-up. I've clicked the magic button on RTD to re-enable the webhook and also added `icemac` as a maintainer.

**Comment by icemac** [comment]
Thank you!
