### ISSUE TITLE
SMTP support for TLS over port 465 is needed

### ISSUE THREAD

**Issue by MrTango** [zopefoundation/zope.sendmail#53]
## currently sending over SSL/TLS over port 465 is not working

Since the the RFC was update in 2018 to deprecate STARTTLS (port 587) in favor of SSL/TLS (port 465), we should support sending over port 465. Some email providers like AWS don't support it anymore and this becomes a problem.

https://www.rfc-editor.org/rfc/rfc8314

We need to import `smtplib.SMTP_SSL` instead of `smtplib.SMTP` to support that port.
If we want to support both, we need to use one or the other depending on which port was configured.
Any opinions?

**Comment by d-maurer** [comment]
Maik Derstappen wrote at 2024-2-8 08:33 -0800:
> ...
>If we want to support both, we need to use one or the other depending on which port was configured.
>Any opinions?

I do not think we should base a decision on the port (my primary
mail provider for example uses non standard ports)
Instead, we should have an option destinquishing between
"starttls" and "smtps".

**Comment by icemac** [comment]
Fixed by #54.

**Comment by icemac** [comment]
Released in https://pypi.org/project/zope.sendmail/6.2/
